spring.application.name=ms-pedidos

spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.dtudhbhgymaimhddyotx
spring.datasource.password=FQFqnoR17PONJji7
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.use_get_generated_keys=false

server.port=8082

spring.datasource.hikari.connection-init-sql=SET search_path=public
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=2

ms-catalogo.url=http://localhost:8081