spring.application.name=ms-pedidos

# Conexion a Supabase (Postgres) - Shared Pooler
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.dtudhbhgymaimhddyotx
spring.datasource.password=FQFqnoR17PONJji7
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Este microservicio corre en el puerto 8082 (ms-catalogo usa 8081)
server.port=8082

# URL del microservicio ms-catalogo (para pedir datos de juegos)
ms-catalogo.url=http://localhost:8081

# Hikari
spring.datasource.hikari.connection-init-sql=SET search_path=public
spring.jpa.properties.hibernate.jdbc.use_get_generated_keys=false
